name: Nuget Package Publish

on: 
  workflow_dispatch :

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - run: dotnet new console --name HarryNugetPublish    
    - run: dotnet pack ./AppLogger/AppLogger.csproj --configuration Release
    - run: dotnet nuget push "bin/Release/**.nupkg"  --api-key YOUR_GITHUB_PAT --source "github"
